"""edit the user author follow table

Revision ID: 03d34eb727da
Revises: 4ceba4eabaca
Create Date: 2025-10-20 14:52:18.877801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '03d34eb727da'
down_revision: Union[str, Sequence[str], None] = '4ceba4eabaca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users_follow_authors', ['user_id', 'author_id'])
    op.drop_constraint(op.f('users_follow_authors_ibfk_2'), 'users_follow_authors', type_='foreignkey')
    op.drop_constraint(op.f('users_follow_authors_ibfk_1'), 'users_follow_authors', type_='foreignkey')
    op.create_foreign_key(None, 'users_follow_authors', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'users_follow_authors', 'authors', ['author_id'], ['id'])
    op.drop_column('users_follow_authors', 'updated_at')
    op.drop_column('users_follow_authors', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_follow_authors', sa.Column('created_at', mysql.DATETIME(), nullable=True))
    op.add_column('users_follow_authors', sa.Column('updated_at', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'users_follow_authors', type_='foreignkey')
    op.drop_constraint(None, 'users_follow_authors', type_='foreignkey')
    op.create_foreign_key(op.f('users_follow_authors_ibfk_1'), 'users_follow_authors', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('users_follow_authors_ibfk_2'), 'users_follow_authors', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users_follow_authors', type_='unique')
    # ### end Alembic commands ###
