"""add new post_report table

Revision ID: 127df6239836
Revises: 54e9ff00cfdc
Create Date: 2025-10-11 21:10:23.897963

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '127df6239836'
down_revision: Union[str, Sequence[str], None] = '54e9ff00cfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
