"""edit you can clear post but you don'd clear report

Revision ID: 24445d5cebee
Revises: 6ba9648fc5ba
Create Date: 2025-12-17 00:27:53.505883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '24445d5cebee'
down_revision: Union[str, Sequence[str], None] = '6ba9648fc5ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_reports', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.alter_column('post_reports', 'post_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
