"""edit notifications table

Revision ID: 354d038c7910
Revises: 24445d5cebee
Create Date: 2025-12-18 01:11:24.221515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '354d038c7910'
down_revision: Union[str, Sequence[str], None] = '24445d5cebee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('notifications_ibfk_1'), 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('recipient_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('notifications_ibfk_1'), 'notifications', 'users', ['recipient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
