"""add new post_report table first

Revision ID: 3ef9d2644353
Revises: 127df6239836
Create Date: 2025-10-11 21:16:08.885137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ef9d2644353'
down_revision: Union[str, Sequence[str], None] = '127df6239836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_post_reports_user_post')
    )
    op.create_index('ix_post_reports_created_at', 'post_reports', ['created_at'], unique=False)
    op.create_index('ix_post_reports_post_id', 'post_reports', ['post_id'], unique=False)
    op.create_index('ix_post_reports_user_id', 'post_reports', ['user_id'], unique=False)
    op.create_table('post_views',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('first_view_at', sa.DateTime(), nullable=True),
    sa.Column('last_view_at', sa.DateTime(), nullable=True),
    sa.Column('count_views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id', name='uq_post_views_user_post')
    )
    op.create_index('ix_post_views_last_viewed_at', 'post_views', ['last_view_at'], unique=False)
    op.create_index('ix_post_views_post_id', 'post_views', ['post_id'], unique=False)
    op.create_index('ix_post_views_user_id', 'post_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_views_user_id', table_name='post_views')
    op.drop_index('ix_post_views_post_id', table_name='post_views')
    op.drop_index('ix_post_views_last_viewed_at', table_name='post_views')
    op.drop_table('post_views')
    op.drop_index('ix_post_reports_user_id', table_name='post_reports')
    op.drop_index('ix_post_reports_post_id', table_name='post_reports')
    op.drop_index('ix_post_reports_created_at', table_name='post_reports')
    op.drop_table('post_reports')
    # ### end Alembic commands ###
