"""add field bio to author table

Revision ID: 3fd444b155fb
Revises: babda01caee0
Create Date: 2025-10-23 23:37:51.601399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fd444b155fb'
down_revision: Union[str, Sequence[str], None] = 'babda01caee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('authors', sa.Column('bio', sa.Text(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('authors', 'bio')
    # ### end Alembic commands ###
