"""create all table the fourth

Revision ID: 5d16b01a441d
Revises: e0eb992204a0
Create Date: 2025-10-11 20:22:54.096425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d16b01a441d'
down_revision: Union[str, Sequence[str], None] = 'e0eb992204a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'posts', ['post_id'], ['post_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'post_id')
    # ### end Alembic commands ###
