"""edit user table

Revision ID: 5dac8e070763
Revises: b997269c5d90
Create Date: 2025-10-16 21:22:29.532905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dac8e070763'
down_revision: Union[str, Sequence[str], None] = 'b997269c5d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_post_views_user_id', 'post_views', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_views_user_id', table_name='post_views')
    # ### end Alembic commands ###
