"""add two collumn is cover_url and username for user table

Revision ID: 6ba9648fc5ba
Revises: fb0d7656f9c2
Create Date: 2025-12-01 16:32:33.003099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ba9648fc5ba'
down_revision: Union[str, Sequence[str], None] = 'fb0d7656f9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cover_url', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_column('users', 'cover_url')
    # ### end Alembic commands ###
