"""deleted column published time because it had already in the post table

Revision ID: cba3ce3a9c82
Revises: 4a8832ce4c89
Create Date: 2025-11-17 14:55:30.163397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cba3ce3a9c82'
down_revision: Union[str, Sequence[str], None] = '4a8832ce4c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
