<<<<<<<< HEAD:alembic/versions/f2fe7acc0864_create_table_author_and_user.py
"""create table author and user

Revision ID: f2fe7acc0864
Revises: 
Create Date: 2025-10-11 15:26:34.074876
========
"""add sessions table

Revision ID: fb0d7656f9c2
Revises: cba3ce3a9c82
Create Date: 2025-11-27 22:55:57.535910
>>>>>>>> main:alembic/versions/fb0d7656f9c2_add_sessions_table.py

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:alembic/versions/f2fe7acc0864_create_table_author_and_user.py
revision: str = 'f2fe7acc0864'
down_revision: Union[str, Sequence[str], None] = None
========
revision: str = 'fb0d7656f9c2'
down_revision: Union[str, Sequence[str], None] = 'cba3ce3a9c82'
>>>>>>>> main:alembic/versions/fb0d7656f9c2_add_sessions_table.py
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:alembic/versions/f2fe7acc0864_create_table_author_and_user.py
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('authors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pen_name', sa.String(length=100), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True),
    sa.Column('biography', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('pen_name')
    )
========
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
>>>>>>>> main:alembic/versions/fb0d7656f9c2_add_sessions_table.py
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<<< HEAD:alembic/versions/f2fe7acc0864_create_table_author_and_user.py
    op.drop_table('authors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
========
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
>>>>>>>> main:alembic/versions/fb0d7656f9c2_add_sessions_table.py
    # ### end Alembic commands ###
